/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.fansin.formatter

import kotlin.test.Test
import kotlin.test.assertEquals

class TableFormatterTest {

    private fun defaultFormatterTest(tableFormatter: TableFormatter, expected: String) {
        tableFormatter.addRow("Test", "test", "testet")
        tableFormatter.addRow("ter", "te")
        tableFormatter.addRow(123, 13, 123)
        tableFormatter.addRow(123.123, 12.0, "test", 123)
        tableFormatter.removeAt(2)
        assertEquals(expected, tableFormatter.format())
    }

    private fun emptyFormatterTest(tableFormatter: TableFormatter) {
        assertEquals("", tableFormatter.format())
    }

    private fun singleFormatterTest(tableFormatter: TableFormatter, expected: String) {
        tableFormatter.addRow("Test")
        assertEquals(expected, tableFormatter.format())
    }

    @Test fun borderlessTest() {
        val expected =
            "Test   \ttest\ttestet\t   \n" +
            "ter    \tte  \t      \t   \n" +
            "123.123\t12.0\ttest  \t123"

        val tableFormatter = TableFormatter.create()
        defaultFormatterTest(tableFormatter, expected)
    }

    @Test fun emptyBorderlessTest() =
        emptyFormatterTest(TableFormatter.create())

    @Test fun singleBorderlessTest() {

        val expected = "Test"

        singleFormatterTest(TableFormatter.create(), expected)
    }


    @Test fun asciiBorderTest() {
        val expected =
            "+-------+----+------+---+\n" +
            "|Test   |test|testet|   |\n" +
            "+-------+----+------+---+\n" +
            "|ter    |te  |      |   |\n" +
            "+-------+----+------+---+\n" +
            "|123.123|12.0|test  |123|\n" +
            "+-------+----+------+---+"

        val tableFormatter =
            TableFormatter.create(AsciiBorderFormatter())
        defaultFormatterTest(tableFormatter, expected)
    }

    @Test fun emptyAsciiBorderTest() =
        emptyFormatterTest(TableFormatter.create(AsciiBorderFormatter()))

    @Test fun singleAsciiBorderTest() {

        val expected =
            "+----+\n" +
            "|Test|\n" +
            "+----+"

        singleFormatterTest(TableFormatter.create(AsciiBorderFormatter()), expected)
    }

    @Test fun unicodeBorderTest() {
        val expected =
            "╔═══════╤════╤══════╤═══╗\n" +
            "║Test   │test│testet│   ║\n" +
            "╠═══════╪════╪══════╪═══╣\n" +
            "║ter    │te  │      │   ║\n" +
            "╟───────┼────┼──────┼───╢\n" +
            "║123.123│12.0│test  │123║\n" +
            "╚═══════╧════╧══════╧═══╝"
        val tableFormatter =
            TableFormatter.create(UnicodeBorderFormatter())
        defaultFormatterTest(tableFormatter, expected)
    }

    @Test fun emptyUnicodeBorderTest() =
        emptyFormatterTest(TableFormatter.create(UnicodeBorderFormatter()))

    @Test fun singleUnicodeBorderTest() {

        val expected =
            "╔════╗\n" +
            "║Test║\n" +
            "╚════╝"

        singleFormatterTest(TableFormatter.create(UnicodeBorderFormatter()), expected)
    }
}
